# プラグインの有効化/無効化
plugin-enabled: true
# どのアイテムを検知するかとその危険度
# "ブロック設置"に関しては設置型ブロックのみ検知可能。
# (溶岩などは直接設置しているわけではないので"設置"検知は不可)
# detectable-itemsの変更時のみ再起動が必要
detectable-items:
  - item: WITHER_SKELETON_SKULL
    danger-level: 3
  - item: LAVA_BUCKET
    danger-level: 4
  - item: FLINT_AND_STEEL
    danger-level: 2
  - item: TNT
    danger-level: 5
  - item: END_CRYSTAL
    danger-level: 4
  - item: COMMAND_BLOCK
    danger-level: 5
# ベッドの使用検知を有効にするかどうか
detect-bed-use: true 
# ここにDiscordのチャンネルIDを入力
discord-channel-id: 'YOUR-DISCORD-CHANNEL-ID' 
# ブロックの着火を検知
detect-ignite-block: true