plugin-enabled: true
detectable-items: # どのアイテムを検知するか
  - WITHER_SKELETON_SKULL
  - LAVA_BUCKET
  - FLINT_AND_STEEL
  - TNT
  - END_CRYSTAL
  - COMMAND_BLOCK
detect-bed-use: true # ベッドの使用検知を有効にするかどうか
discord-channel-id: 'YOUR-DISCORD-CHANNEL-ID' 　　　# ここにDiscordのチャンネルIDを入力
