#  ┌──────────────────────────────────────────────────────────────────────┐
#  │            ____  ____    _    ____  _             _                  │
#  │           / ___||  _ \  / \  |  _ \| |_   _  __ _(_)_ __             │
#  │           \___ \| | | |/ _ \ | |_) | | | | |/ _` | | '_ \            │
#  │            ___) | |_| / ___ \|  __/| | |_| | (_| | | | | |           │
#  │           |____/|____/_/   \_\_|   |_|\__,_|\__, |_|_| |_|           │
#  │                                                   |___/              │
#  │                                                                      │
#  │                          v1.14-release                               │
#  │                                                                      │
#  │                    Created by Soryu-haruma(Asl)                      │
#  └──────────────────────────────────────────────────────────────────────┘
# プラグインの有効化/無効化
plugin-enabled: true
# どのアイテムを検知するかとその危険度
# "ブロック設置"に関しては設置型ブロックのみ検知可能。
# (溶岩などは直接設置しているわけではないので"設置"検知は不可)
# 危険度は1~5の整数で設定
# 1:白 2:黄 3:赤 4:濃い赤 5:紫
# detectable-itemsの変更時のみ再起動が必要
detectable-items:
  - item: WITHER_SKELETON_SKULL
    danger-level: 3
  - item: LAVA_BUCKET
    danger-level: 4
  - item: FLINT_AND_STEEL
    danger-level: 2
  - item: TNT
    danger-level: 5
  - item: END_CRYSTAL
    danger-level: 4
  - item: COMMAND_BLOCK
    danger-level: 5
# ベッドの使用検知を有効にするかどうか
detect-bed-use: true 
# ここにDiscordのチャンネルIDを入力
discord-channel-id: 'YOUR-DISCORD-CHANNEL-ID' 
# ブロックの着火を検知
detect-ignite-block: true
# 溶岩バケツの使用を検知
detect-lavabucket-use: true
# 通知のクールタイム（秒単位）デフォルトでは1秒
notification-cooldown: 1

# 試す方法が無いので、検知するかどうかわかりません。
# コマンド通知を有効にするかどうか
enable-notify-commands: true
# 通知を送信するコマンドのリスト
# 例:
# notify-commands:
#  - op
#  - deop
#  - ban
notify-commands:
  - op
  - deop
  - ban
# デバッグモード
debug-mode: false

# ここは変更しないでください。
language-identifier: ja
# Author: Soryu-haruma(Asl,haruma9012kirby)