name: SDA
version: 1.1
main: com.example.sda.SDAPlugin
api-version: 1.21
commands:
  sda:
    description: SDAプラグインを操作するコマンド
    usage: /<command> <on|off|reload>
    permission: sda.use
permissions:
  sda.use:
    description: SDAプラグインを使用するためのパーミッション
    default: op
  sda.bypass:
    description: 検知をバイパス
    default: op
