name: SDA
version: 1.15-beta
main: com.example.sda.SDAPlugin
author: Soryu-haruma(Asl)
description: 危険なアイテムの設置などを検知してDiscordに通知を送信
api-version: 1.21
commands:
  sda:
    description: SDAプラグインを操作するコマンド
    usage: |
     Usage: /sda <command>
      - on : プラグインを有効化
      - off : プラグインを無効化
      - reload : configファイルを再読み込み
      - test : テストメッセージをDiscordに送信
    permission: sda.use
permissions:
  sda.use:
    description: SDAプラグインを使用するためのパーミッション
    default: op
  sda.bypass:
    description: 検知をバイパス
    default: op
